### ISSUE TITLE
[styling] Consider keeping the branding of the JMESPath logo

### ISSUE THREAD

**Issue by springcomp** [jmespath-unofficial/jmespath.jep#64]
This is part of a [series or minor issues](/jmespath-community/jmespath.spec/labels/css-styling) that aim to enable support for flexible styling and theming of the JMESPath site.

I feel the JMESPath logo is part of the original branding and should not be changed,
Here is the original logo:

![image](https://user-images.githubusercontent.com/8488398/164195295-57c3b0b5-e7e3-4192-9695-34514f1f5960.png)

Here is the new logo:

![image](https://user-images.githubusercontent.com/8488398/164195238-d06e7db7-c556-444b-935b-7e8274d16c7c.png)

In particular the "Path" portion of the logo used to be in all uppercase. Whereas the "JME" portion of the logo used to be formatted with a very thin font.

**Comment by innovate-invent** [comment]
I took some artistic liberty to resolve some minor issues. 

Everywhere else JMESPath is written, it is lowercase "ath". I felt it would be good to make it consistent and helps make it visually distinct from the JMES portion. I also extended the J to hang down to visually incorporate the "Community Edition" subheading. "JME" was made thicker to improve readability, especially when it is displayed at a smaller size. "Path" was changed to black from white to be compatible with a transparent background, this allows it to better integrate with surrounding styling rather than forcing a background color. I still need to produce a stylesheet for the svg that will allow swapping the colors for compatibility with a dark background.

Is there a downside to taking this opportunity to update the the branding? The changes are minor enough that it is still recognizable with the original. I think that we should make some effort to not confuse people between our fork and James'.

I am not married to any of these changes if you feel we really should stick to the original logo.

**Comment by springcomp** [comment]
I guess you have some good reasoning behind the changes you made.
Maybe let's keep it as you've done. We will always be able to respond to feedback from the community, if any at all.

**Comment by innovate-invent** [comment]
![jmespath](https://user-images.githubusercontent.com/1768820/164293949-1de9b233-6c0f-4a65-9f8b-5ba1851d6309.png)


Here is a prototype with the uppercase path

**Comment by springcomp** [comment]
> Here is a prototype with the uppercase path
I admit to prefer this one 😏

**Comment by innovate-invent** [comment]
sure, I will swap that one into the repo
